version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    network_mode: host
    privileged: true
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m "
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    network_mode: host
    privileged: true
    environment:
      ELASTICSEARCH_HOSTS: http://localhost:9200
    ports:
      - "5601:5601"
  apm:
    image: docker.elastic.co/apm/apm-server:7.10.1
    network_mode: "host"
    privileged: true
    volumes:
      - "./apm-server.yml:/usr/share/apm-server/apm-server.yml"
      - "./definition.json:/usr/share/apm-server/ingest/pipeline/definition.json"
